#!/bin/sh

## General ---------------------------------------------------#

# Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

## Configurations --------------------------------------------#

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5'
		let name++
	done
}
workspaces

# Window information
bspc config border_width 2 
bspc config window_gap 8
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# Border Colors
bspc config normal_border_color #6C7086
bspc config active_border_color #B4BEFE
bspc config focused_border_color #A6E3A1

# Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

# Monocle layout
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle false
bspc config single_monocle false

# Padding to leave space for bar
bspc config bottom_padding 0
bspc config top_padding 20

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

## Autostart -------------------------------------------------#
# xrandr -s 1920x1080 &				# Set resolution
pgrep -x sxhkd > /dev/null || sxhkd &		# Restart shortcuts

pkill picom 					# Kill picom
picom & # --experimental-backends &		# Restart picom

dunst &						# Start Notifications
flameshot &					# Start Flameshot
feh --bg-fill ~/Pictures/bg.jpg &		# Set wallpaper
# ~/.config/polybar/launch.sh &			# Start polybar
