#!/usr/bin/env python3

from typing import List
from pathlib import Path
import argparse
import os

def create_symlink(directory: Path, config_dir: Path = Path.home() / '.config'):
    try:
        symlink_path = config_dir / directory.name
        symlink_path = symlink_path.resolve()

        os.symlink(directory, symlink_path)
        print(f"Created symlink for {directory.name}")

    except Exception as e:
        print(f"An error occurred: {e}")

def main():
    parser = argparse.ArgumentParser(description="Create symlinks for dotfiles.")
    parser.add_argument("directories", nargs="*", help="Specify directories to create symlinks for.")

    args = parser.parse_args()

    home_dir = Path.home()
    dotfiles_dir = home_dir / 'SfikasTeo' / 'dotfiles'

    if args.directories:
        for directory_name in args.directories:
            directory_path = (dotfiles_dir / directory_name).resolve()
            if directory_path.exists():
                create_symlink(directory_path)
            else:
                print(f"Directory '{directory_name}' does not exist.")
    else:
        directories = [
                    (dotfiles_dir / 'helix').resolve(),
                    (dotfiles_dir / 'hypr').resolve(),
                    (dotfiles_dir / 'rofi').resolve(),
                    (dotfiles_dir / 'zsh').resolve(),
                ]

        for directory in directories:
            create_symlink(directory)

if __name__ == "__main__":
    main()

